defmodule FantasyManager.Fantasy.WaiverRecommendation do
  @moduledoc """
  Represents AI-generated waiver pickup and drop recommendations.
  
  Generated by the RecommendationEngine based on team needs, player performance,
  trending data, and AI analysis.
  """
  
  use Ash.Resource,
    domain: FantasyManager.Fantasy,
    data_layer: AshPostgres.DataLayer

  postgres do
    table "waiver_recommendations"
    repo FantasyManager.Repo
  end

  attributes do
    uuid_primary_key :id

    attribute :team_id, :string do
      allow_nil? false
      public? true
    end

    attribute :player_id, :string do
      allow_nil? false
      public? true
    end

    attribute :player_name, :string do
      allow_nil? false
      public? true
    end

    attribute :position, :string do
      allow_nil? false
      public? true
    end

    attribute :team, :string do
      public? true
    end

    attribute :recommendation_type, :string do
      allow_nil? false
      public? true
    end

    attribute :priority_score, :decimal do
      allow_nil? false
      public? true
    end

    attribute :reasoning, :string do
      allow_nil? false
      public? true
    end

    attribute :drop_candidate, :string do
      allow_nil? true
      public? true
    end

    attribute :status, :string do
      allow_nil? false
      public? true
      default "pending"
    end

    attribute :week, :integer do
      allow_nil? false
      public? true
    end

    attribute :season, :integer do
      allow_nil? false
      public? true
    end

    attribute :generated_at, :naive_datetime do
      allow_nil? false
      public? true
    end

    attribute :expires_at, :naive_datetime do
      public? true
    end

    create_timestamp :inserted_at
    update_timestamp :updated_at
  end

  actions do
    defaults [:read, :destroy]

    create :create do
      primary? true
      accept [
        :team_id,
        :player_id,
        :player_name,
        :position,
        :team,
        :recommendation_type,
        :priority_score,
        :reasoning,
        :drop_candidate,
        :status,
        :week,
        :season,
        :generated_at,
        :expires_at
      ]
    end

    update :update do
      primary? true
      accept [
        :status
      ]
    end

    update :update_status do
      accept [:status]
    end

    read :get do
      argument :id, :uuid, allow_nil?: false
      filter expr(id == ^arg(:id))
    end
  end

  validations do
    validate present([:team_id, :player_id, :player_name, :position, :recommendation_type, :priority_score, :reasoning, :week, :season, :generated_at])
  end

  preparations do
    prepare build(sort: [priority_score: :desc, generated_at: :desc])
  end

  code_interface do
    domain FantasyManager.Fantasy
    define :create
    define :read
    define :update
    define :update_status
    define :destroy
    define :get
  end
end